name: Full Build CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'shell/**'
      - 'remote1/**'
      - 'remote2/**'
      - 'shared-lib/**'

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (from root)
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build shell
        run: ng build
        working-directory: shell

      - name: Build remote1
        run: ng build
        working-directory: remote1

      - name: Build remote2
        run: ng build
        working-directory: remote2
