name: Remote 2 CI

on:
  push:
    branches: [master]
    paths:
      - 'remote2/**'
      - 'shared-lib/**'
  pull_request:
    branches: [master]
    paths:
      - 'remote2/**'
      - 'shared-lib/**'
  workflow_dispatch:  # ← это добавляет кнопку "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build remote2
        run: ng build
        working-directory: remote2

