name: Shell CI

on:
  push:
    branches: [master]
    paths:
      - 'shell/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shell
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
